"""
SignalixAI Python SDK for Strategy Development

Provides base classes, decorators, and utilities for building trading strategies.
This is the API available to user code in the Code Sandbox.

Requirements: 37.1, 37.2, 37.3, 37.4, 37.5, 37.6, 37.7, 37.8, 37.9, 37.10
"""
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Callable, Any, Union
from dataclasses import dataclass
from datetime import datetime
import logging

# Configure logging for strategies
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("signalixai")


# ============================================================================
# Data Classes
# ============================================================================

@dataclass
class MarketData:
    """Market data for a single bar/tick"""
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: Optional[float] = None
    oi: Optional[int] = None  # Open interest for futures/options


@dataclass
class TickData:
    """Tick-level market data"""
    symbol: str
    timestamp: datetime
    price: float
    quantity: int
    side: str  # 'buy' or 'sell'


@dataclass
class Signal:
    """Trading signal generated by strategy"""
    action: str  # 'buy', 'sell', 'exit_long', 'exit_short'
    symbol: str
    quantity: Union[int, float]
    price: Optional[float] = None
    order_type: str = "market"  # 'market', 'limit', 'stop', 'stop_limit'
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop: Optional[float] = None
    reason: str = ""
    timestamp: Optional[datetime] = None


@dataclass
class Position:
    """Current position information"""
    symbol: str
    side: str  # 'long', 'short', 'flat'
    quantity: Union[int, float]
    avg_entry_price: float
    current_price: float
    unrealized_pnl: float
    realized_pnl: float


@dataclass
class Order:
    """Order information"""
    order_id: str
    symbol: str
    action: str
    quantity: Union[int, float]
    price: Optional[float]
    order_type: str
    status: str  # 'pending', 'open', 'filled', 'cancelled', 'rejected'
    filled_qty: Union[int, float] = 0
    filled_price: Optional[float] = None
    timestamp: datetime = None


# ============================================================================
# Decorators
# ============================================================================

def on_bar(func: Callable) -> Callable:
    """
    Decorator to mark a method as the on_bar event handler.
    Called on every new bar/candle close.
    
    Example:
        @on_bar
        def on_bar(self, data):
            if self.indicators.rsi(14) < 30:
                self.buy()
    """
    func._is_on_bar = True
    return func


def on_tick(func: Callable) -> Callable:
    """
    Decorator to mark a method as the on_tick event handler.
    Called on every tick (optional, for high-frequency strategies).
    
    Example:
        @on_tick
        def on_tick(self, tick):
            if tick.price > self.last_price * 1.01:
                self.buy()
    """
    func._is_on_tick = True
    return func


def on_order_update(func: Callable) -> Callable:
    """
    Decorator to mark a method as the on_order_update event handler.
    Called when order status changes.
    
    Example:
        @on_order_update
        def on_order_update(self, order):
            if order.status == 'filled':
                self.log(f"Order filled: {order.filled_qty} @ {order.filled_price}")
    """
    func._is_on_order_update = True
    return func


def on_position_change(func: Callable) -> Callable:
    """
    Decorator to mark a method as the on_position_change event handler.
    Called when position changes.
    
    Example:
        @on_position_change
        def on_position_change(self, position):
            if position.side == 'long':
                self.stop_loss = position.avg_entry_price * 0.95
    """
    func._is_on_position_change = True
    return func


# ============================================================================
# Indicators Helper Class
# ============================================================================

class Indicators:
    """
    Technical indicators helper class.
    Provides access to TA-Lib functions and custom indicators.
    """
    
    def __init__(self, data_provider: Any):
        self._data = data_provider
        self._cache: Dict[str, Any] = {}
    
    def _get_series(self, field: str = 'close', period: int = 100) -> List[float]:
        """Get historical price series"""
        return self._data.get_series(field, period)
    
    def sma(self, period: int = 20, field: str = 'close') -> float:
        """Simple Moving Average"""
        series = self._get_series(field, period)
        if len(series) < period:
            return series[-1] if series else 0.0
        return sum(series[-period:]) / period
    
    def ema(self, period: int = 20, field: str = 'close') -> float:
        """Exponential Moving Average"""
        series = self._get_series(field, period * 2)
        if len(series) < period:
            return series[-1] if series else 0.0
        
        multiplier = 2 / (period + 1)
        ema = series[0]
        for price in series[1:]:
            ema = (price - ema) * multiplier + ema
        return ema
    
    def rsi(self, period: int = 14) -> float:
        """
        Relative Strength Index
        Returns RSI value between 0-100
        """
        closes = self._get_series('close', period * 2)
        if len(closes) < period + 1:
            return 50.0  # Neutral
        
        gains = []
        losses = []
        
        for i in range(1, len(closes)):
            change = closes[i] - closes[i-1]
            if change > 0:
                gains.append(change)
                losses.append(0)
            else:
                gains.append(0)
                losses.append(abs(change))
        
        if len(gains) < period:
            return 50.0
        
        avg_gain = sum(gains[-period:]) / period
        avg_loss = sum(losses[-period:]) / period
        
        if avg_loss == 0:
            return 100.0
        
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))
        return rsi
    
    def macd(self, fast: int = 12, slow: int = 26, signal: int = 9) -> Dict[str, float]:
        """
        MACD (Moving Average Convergence Divergence)
        Returns dict with 'macd', 'signal', 'histogram'
        """
        closes = self._get_series('close', slow + signal)
        
        ema_fast = self._calculate_ema(closes, fast)
        ema_slow = self._calculate_ema(closes, slow)
        
        macd_line = ema_fast - ema_slow
        signal_line = self._calculate_ema([macd_line] * (signal + 1), signal)
        histogram = macd_line - signal_line
        
        return {
            'macd': macd_line,
            'signal': signal_line,
            'histogram': histogram
        }
    
    def _calculate_ema(self, data: List[float], period: int) -> float:
        """Helper to calculate EMA from a list"""
        if len(data) < period:
            return data[-1] if data else 0.0
        
        multiplier = 2 / (period + 1)
        ema = sum(data[:period]) / period
        
        for price in data[period:]:
            ema = (price - ema) * multiplier + ema
        
        return ema
    
    def bollinger_bands(self, period: int = 20, std_dev: float = 2.0) -> Dict[str, float]:
        """
        Bollinger Bands
        Returns dict with 'upper', 'middle', 'lower'
        """
        closes = self._get_series('close', period)
        if len(closes) < period:
            current = closes[-1] if closes else 0.0
            return {'upper': current, 'middle': current, 'lower': current}
        
        middle = sum(closes[-period:]) / period
        variance = sum((x - middle) ** 2 for x in closes[-period:]) / period
        std = variance ** 0.5
        
        return {
            'upper': middle + (std_dev * std),
            'middle': middle,
            'lower': middle - (std_dev * std)
        }
    
    def atr(self, period: int = 14) -> float:
        """
        Average True Range
        Volatility indicator
        """
        highs = self._get_series('high', period + 1)
        lows = self._get_series('low', period + 1)
        closes = self._get_series('close', period + 1)
        
        if len(highs) < 2:
            return 0.0
        
        true_ranges = []
        for i in range(1, len(highs)):
            tr1 = highs[i] - lows[i]
            tr2 = abs(highs[i] - closes[i-1])
            tr3 = abs(lows[i] - closes[i-1])
            true_ranges.append(max(tr1, tr2, tr3))
        
        if len(true_ranges) < period:
            return sum(true_ranges) / len(true_ranges) if true_ranges else 0.0
        
        return sum(true_ranges[-period:]) / period
    
    def adx(self, period: int = 14) -> float:
        """
        Average Directional Index
        Trend strength indicator (0-100)
        """
        # Simplified ADX calculation
        highs = self._get_series('high', period * 2)
        lows = self._get_series('low', period * 2)
        
        if len(highs) < period * 2:
            return 25.0  # Neutral
        
        # Calculate +DM and -DM
        plus_dm = []
        minus_dm = []
        
        for i in range(1, len(highs)):
            up_move = highs[i] - highs[i-1]
            down_move = lows[i-1] - lows[i]
            
            if up_move > down_move and up_move > 0:
                plus_dm.append(up_move)
                minus_dm.append(0)
            elif down_move > up_move and down_move > 0:
                plus_dm.append(0)
                minus_dm.append(down_move)
            else:
                plus_dm.append(0)
                minus_dm.append(0)
        
        if len(plus_dm) < period:
            return 25.0
        
        atr_val = self.atr(period)
        if atr_val == 0:
            return 25.0
        
        plus_di = 100 * sum(plus_dm[-period:]) / (period * atr_val)
        minus_di = 100 * sum(minus_dm[-period:]) / (period * atr_val)
        
        dx = 100 * abs(plus_di - minus_di) / (plus_di + minus_di) if (plus_di + minus_di) > 0 else 0
        return dx
    
    def stochastic(self, k_period: int = 14, d_period: int = 3) -> Dict[str, float]:
        """
        Stochastic Oscillator
        Returns dict with '%K' and '%D'
        """
        highs = self._get_series('high', k_period)
        lows = self._get_series('low', k_period)
        closes = self._get_series('close', k_period)
        
        if len(highs) < k_period:
            return {'%K': 50.0, '%D': 50.0}
        
        highest_high = max(highs[-k_period:])
        lowest_low = min(lows[-k_period:])
        current_close = closes[-1]
        
        if highest_high == lowest_low:
            k = 50.0
        else:
            k = 100 * (current_close - lowest_low) / (highest_high - lowest_low)
        
        # Simplified %D (using last k values)
        d = k  # In full implementation, this would be SMA of %K
        
        return {'%K': k, '%D': d}
    
    def vwap(self) -> float:
        """
        Volume Weighted Average Price
        """
        highs = self._get_series('high', 100)
        lows = self._get_series('low', 100)
        closes = self._get_series('close', 100)
        volumes = self._get_series('volume', 100)
        
        if not volumes or sum(volumes) == 0:
            return closes[-1] if closes else 0.0
        
        typical_prices = [(h + l + c) / 3 for h, l, c in zip(highs, lows, closes)]
        vwap = sum(tp * vol for tp, vol in zip(typical_prices, volumes)) / sum(volumes)
        
        return vwap


# ============================================================================
# Strategy Base Class
# ============================================================================

class Strategy(ABC):
    """
    Base class for all trading strategies.
    
    Extend this class and implement on_bar() method to create your strategy.
    
    Example:
        class MyStrategy(Strategy):
            def __init__(self):
                super().__init__()
                self.rsi_period = 14
            
            @on_bar
            def on_bar(self, data):
                rsi = self.indicators.rsi(self.rsi_period)
                if rsi < 30:
                    self.buy(qty=1)
    """
    
    def __init__(self):
        self.name = self.__class__.__name__
        self.parameters: Dict[str, Any] = {}
        self.indicators: Optional[Indicators] = None
        self.data_provider: Optional[Any] = None
        
        # State
        self._position: Optional[Position] = None
        self._orders: List[Order] = []
        self._signals: List[Signal] = []
        self._logs: List[str] = []
        self._equity: float = 0.0
        self._cash: float = 0.0
        
        # Risk management
        self.max_position_size: Union[int, float] = float('inf')
        self.max_daily_loss: float = float('inf')
        self.stop_loss_pct: Optional[float] = None
        self.take_profit_pct: Optional[float] = None
        
        self._discover_handlers()
    
    def _discover_handlers(self):
        """Discover and store event handler methods"""
        self._on_bar_handler = None
        self._on_tick_handler = None
        self._on_order_update_handler = None
        self._on_position_change_handler = None
        
        for attr_name in dir(self):
            attr = getattr(self, attr_name)
            if callable(attr):
                if hasattr(attr, '_is_on_bar'):
                    self._on_bar_handler = attr
                elif hasattr(attr, '_is_on_tick'):
                    self._on_tick_handler = attr
                elif hasattr(attr, '_is_on_order_update'):
                    self._on_order_update_handler = attr
                elif hasattr(attr, '_is_on_position_change'):
                    self._on_position_change_handler = attr
    
    def initialize(self, data_provider: Any, initial_cash: float = 100000.0):
        """Initialize strategy with data provider"""
        self.data_provider = data_provider
        self.indicators = Indicators(data_provider)
        self._cash = initial_cash
        self._equity = initial_cash
    
    # ========================================================================
    # Trading Actions
    # ========================================================================
    
    def buy(self, qty: Union[int, float] = 1, price: Optional[float] = None,
            order_type: str = "market", **kwargs) -> Optional[Signal]:
        """
        Place a buy order
        
        Args:
            qty: Quantity to buy
            price: Limit price (for limit orders)
            order_type: 'market', 'limit', 'stop', 'stop_limit'
            **kwargs: Additional order parameters (stop_loss, take_profit, etc.)
        
        Returns:
            Signal object if order was generated
        """
        # Check position size limit
        if self._position and self._position.side == 'long':
            new_qty = self._position.quantity + qty
            if new_qty > self.max_position_size:
                self.log(f"Buy rejected: would exceed max position size {self.max_position_size}")
                return None
        
        signal = Signal(
            action='buy',
            symbol=self._get_symbol(),
            quantity=qty,
            price=price,
            order_type=order_type,
            stop_loss=kwargs.get('stop_loss'),
            take_profit=kwargs.get('take_profit'),
            trailing_stop=kwargs.get('trailing_stop'),
            reason=kwargs.get('reason', ''),
            timestamp=datetime.now()
        )
        
        self._signals.append(signal)
        self.log(f"BUY signal: {qty} @ {price or 'market'}")
        return signal
    
    def sell(self, qty: Union[int, float] = 1, price: Optional[float] = None,
             order_type: str = "market", **kwargs) -> Optional[Signal]:
        """
        Place a sell order
        
        Args:
            qty: Quantity to sell (negative for short selling)
            price: Limit price
            order_type: 'market', 'limit', 'stop', 'stop_limit'
            **kwargs: Additional order parameters
        
        Returns:
            Signal object if order was generated
        """
        # Check if we have position to sell
        if not self._position or self._position.side != 'long':
            self.log("Sell rejected: no long position to exit")
            return None
        
        if qty > self._position.quantity:
            qty = self._position.quantity
        
        signal = Signal(
            action='sell',
            symbol=self._get_symbol(),
            quantity=qty,
            price=price,
            order_type=order_type,
            reason=kwargs.get('reason', ''),
            timestamp=datetime.now()
        )
        
        self._signals.append(signal)
        self.log(f"SELL signal: {qty} @ {price or 'market'}")
        return signal
    
    def exit_position(self, **kwargs) -> Optional[Signal]:
        """
        Exit current position (either long or short)
        
        Returns:
            Signal object if position was exited
        """
        if not self._position or self._position.side == 'flat':
            self.log("Exit rejected: no open position")
            return None
        
        if self._position.side == 'long':
            return self.sell(qty=self._position.quantity, reason="Exit position", **kwargs)
        else:
            # Short position - would need buy_to_cover
            self.log("Exit short position - not yet implemented")
            return None
    
    def cancel_all_orders(self) -> List[str]:
        """Cancel all pending orders"""
        cancelled = []
        for order in self._orders:
            if order.status == 'pending':
                order.status = 'cancelled'
                cancelled.append(order.order_id)
        self.log(f"Cancelled {len(cancelled)} orders")
        return cancelled
    
    # ========================================================================
    # Position Information
    # ========================================================================
    
    def get_position(self) -> Optional[Position]:
        """Get current position information"""
        return self._position
    
    def is_in_position(self) -> bool:
        """Check if strategy has an open position"""
        return self._position is not None and self._position.side != 'flat'
    
    def is_long(self) -> bool:
        """Check if currently in long position"""
        return self._position is not None and self._position.side == 'long'
    
    def is_short(self) -> bool:
        """Check if currently in short position"""
        return self._position is not None and self._position.side == 'short'
    
    def get_quantity(self) -> Union[int, float]:
        """Get current position quantity"""
        if self._position:
            return self._position.quantity
        return 0
    
    def get_pnl(self) -> Dict[str, float]:
        """Get current P&L information"""
        if not self._position:
            return {'unrealized': 0.0, 'realized': 0.0, 'total': 0.0}
        
        return {
            'unrealized': self._position.unrealized_pnl,
            'realized': self._position.realized_pnl,
            'total': self._position.unrealized_pnl + self._position.realized_pnl
        }
    
    # ========================================================================
    # Utility Methods
    # ========================================================================
    
    def log(self, message: str) -> None:
        """Log a message (appears in strategy logs)"""
        timestamp = datetime.now().strftime("%H:%M:%S")
        log_entry = f"[{timestamp}] {message}"
        self._logs.append(log_entry)
        logger.info(f"{self.name}: {message}")
    
    def get_logs(self) -> List[str]:
        """Get all strategy logs"""
        return self._logs.copy()
    
    def clear_logs(self) -> None:
        """Clear strategy logs"""
        self._logs.clear()
    
    def get_equity(self) -> float:
        """Get current account equity"""
        return self._equity
    
    def get_cash(self) -> float:
        """Get available cash"""
        return self._cash
    
    def get_signals(self) -> List[Signal]:
        """Get all generated signals (and clear them)"""
        signals = self._signals.copy()
        self._signals.clear()
        return signals
    
    def _get_symbol(self) -> str:
        """Get current trading symbol"""
        if self.data_provider:
            return getattr(self.data_provider, 'symbol', 'UNKNOWN')
        return 'UNKNOWN'
    
    # ========================================================================
    # Event Handlers (to be implemented by subclasses)
    # ========================================================================
    
    def on_bar(self, data: MarketData) -> None:
        """
        Called on every new bar/candle close.
        Override this method or use @on_bar decorator.
        
        Args:
            data: MarketData for the completed bar
        """
        if self._on_bar_handler:
            self._on_bar_handler(self, data)
    
    def on_tick(self, tick: TickData) -> None:
        """
        Called on every tick.
        Override this method or use @on_tick decorator.
        
        Args:
            tick: TickData for the tick
        """
        if self._on_tick_handler:
            self._on_tick_handler(self, tick)
    
    def on_order_update(self, order: Order) -> None:
        """
        Called when order status changes.
        Override this method or use @on_order_update decorator.
        
        Args:
            order: Order with updated status
        """
        if self._on_order_update_handler:
            self._on_order_update_handler(self, order)
    
    def on_position_change(self, position: Position) -> None:
        """
        Called when position changes.
        Override this method or use @on_position_change decorator.
        
        Args:
            position: Updated position information
        """
        self._position = position
        if self._on_position_change_handler:
            self._on_position_change_handler(self, position)


# ============================================================================
# Risk Management Utilities
# ============================================================================

def calculate_position_size(
    capital: float,
    risk_per_trade_pct: float,
    entry_price: float,
    stop_loss_price: float,
    max_position_pct: float = 10.0
) -> Union[int, float]:
    """
    Calculate position size based on risk parameters
    
    Args:
        capital: Total trading capital
        risk_per_trade_pct: Risk percentage per trade (e.g., 1.0 for 1%)
        entry_price: Planned entry price
        stop_loss_price: Stop loss price
        max_position_pct: Maximum position size as % of capital
    
    Returns:
        Recommended position quantity
    """
    risk_amount = capital * (risk_per_trade_pct / 100)
    risk_per_unit = abs(entry_price - stop_loss_price)
    
    if risk_per_unit == 0:
        return 0
    
    position_size = risk_amount / risk_per_unit
    
    # Apply max position cap
    max_position_value = capital * (max_position_pct / 100)
    max_qty = max_position_value / entry_price
    
    return min(position_size, max_qty)


def kelly_criterion(
    win_rate: float,
    avg_win: float,
    avg_loss: float
) -> float:
    """
    Calculate Kelly Criterion optimal position size
    
    Args:
        win_rate: Probability of winning (0.0 to 1.0)
        avg_win: Average win amount
        avg_loss: Average loss amount
    
    Returns:
        Kelly fraction (0.0 to 1.0)
    """
    if avg_loss == 0:
        return 0.0
    
    win_loss_ratio = avg_win / avg_loss
    kelly = win_rate - ((1 - win_rate) / win_loss_ratio)
    
    # Clamp to reasonable range
    return max(0.0, min(kelly, 0.5))  # Cap at 50%


# ============================================================================
# Data Access Utilities
# ============================================================================

def get_historical_data(
    symbol: str,
    timeframe: str = '1D',
    bars: int = 100,
    data_provider: Optional[Any] = None
) -> List[MarketData]:
    """
    Get historical market data
    
    Args:
        symbol: Trading symbol
        timeframe: Bar timeframe ('1m', '5m', '1h', '1D', etc.)
        bars: Number of bars to retrieve
        data_provider: Data provider instance
    
    Returns:
        List of MarketData objects
    """
    if data_provider:
        return data_provider.get_historical(symbol, timeframe, bars)
    return []


def get_current_price(symbol: str, data_provider: Optional[Any] = None) -> float:
    """
    Get current market price for symbol
    
    Args:
        symbol: Trading symbol
        data_provider: Data provider instance
    
    Returns:
        Current price
    """
    if data_provider:
        return data_provider.get_current_price(symbol)
    return 0.0


# ============================================================================
# Export all public symbols
# ============================================================================

__all__ = [
    'Strategy',
    'MarketData',
    'TickData',
    'Signal',
    'Position',
    'Order',
    'Indicators',
    'on_bar',
    'on_tick',
    'on_order_update',
    'on_position_change',
    'calculate_position_size',
    'kelly_criterion',
    'get_historical_data',
    'get_current_price',
]
